/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Product;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author saura
 */
public class CreateJpanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJpanel
     */
    private Product product;
    
    String filePath;
    
    public CreateJpanel(Product product) {
        initComponents();
        this.product=product;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jlabel1 = new javax.swing.JLabel();
        brand = new javax.swing.JLabel();
        model = new javax.swing.JLabel();
        color = new javax.swing.JLabel();
        fueltype = new javax.swing.JLabel();
        mileage = new javax.swing.JLabel();
        bodytype = new javax.swing.JLabel();
        seats = new javax.swing.JLabel();
        year = new javax.swing.JLabel();
        transmission = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        engdisp = new javax.swing.JLabel();
        mileageTxt = new javax.swing.JTextField();
        brandTxt = new javax.swing.JTextField();
        bodyTxt = new javax.swing.JTextField();
        seatsTxt = new javax.swing.JTextField();
        yearTxt = new javax.swing.JTextField();
        transTxt = new javax.swing.JTextField();
        priceTxt = new javax.swing.JTextField();
        serialTxt = new javax.swing.JTextField();
        modelTxt = new javax.swing.JTextField();
        colorTxt = new javax.swing.JTextField();
        fuelTxt = new javax.swing.JTextField();
        serial = new javax.swing.JLabel();
        engdispTxt = new javax.swing.JTextField();
        createButn = new javax.swing.JButton();
        safety = new javax.swing.JLabel();
        wheels = new javax.swing.JLabel();
        brakes = new javax.swing.JLabel();
        safetyTxt = new javax.swing.JTextField();
        wheelTxt = new javax.swing.JTextField();
        brakeTxt = new javax.swing.JTextField();
        upload = new javax.swing.JButton();
        path = new javax.swing.JLabel();

        Jlabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Jlabel1.setText("Enter your Car details");

        brand.setText("Brand");

        model.setText("Model");

        color.setText("Color");

        fueltype.setText("Fuel Type");

        mileage.setText("Mileage");

        bodytype.setText("Body Type");

        seats.setText("No. of Seats");

        year.setText("Mfg. Year");

        transmission.setText("Transmission");

        price.setText("Price");

        engdisp.setText("Engine Displacement");

        brandTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandTxtActionPerformed(evt);
            }
        });

        colorTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorTxtActionPerformed(evt);
            }
        });

        serial.setText("Serial Number");

        createButn.setText("Create");
        createButn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButnActionPerformed(evt);
            }
        });

        safety.setText("Safety Measures");

        wheels.setText("Type of Wheels");

        brakes.setText("Brake Type");

        safetyTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                safetyTxtActionPerformed(evt);
            }
        });

        upload.setText("Upload Image");
        upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(transmission)
                                .addComponent(model)
                                .addComponent(brand)
                                .addComponent(color)
                                .addComponent(fueltype)
                                .addComponent(mileage)
                                .addComponent(bodytype)
                                .addComponent(seats)
                                .addComponent(year)
                                .addComponent(price)
                                .addComponent(engdisp)
                                .addComponent(serial)
                                .addComponent(safety)
                                .addComponent(wheels)
                                .addComponent(brakes))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(upload)))
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mileageTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(serialTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(priceTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(transTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(yearTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(seatsTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(bodyTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(brandTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(modelTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(colorTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(fuelTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(engdispTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(brakeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(safetyTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(wheelTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(path, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(Jlabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(createButn)))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Jlabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brand)
                    .addComponent(brandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(model)
                    .addComponent(modelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(color)
                    .addComponent(colorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fueltype)
                    .addComponent(fuelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mileage)
                    .addComponent(mileageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bodytype)
                    .addComponent(bodyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seats)
                    .addComponent(seatsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(year)
                    .addComponent(yearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transmission)
                    .addComponent(transTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price)
                    .addComponent(priceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(engdisp)
                    .addComponent(engdispTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(serial)
                    .addComponent(serialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(safety, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wheelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(wheels, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(safetyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(brakes)
                    .addComponent(brakeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(upload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(path, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createButn)
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void brandTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandTxtActionPerformed

    private void colorTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorTxtActionPerformed

    private void createButnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButnActionPerformed
        product.setBrand(brandTxt.getText());
        product.setModel(modelTxt.getText());
        product.setColor(colorTxt.getText());
        product.setFueltype(fuelTxt.getText());
        product.setMileage(mileageTxt.getText());
        product.setBodytype(bodyTxt.getText());
        product.setSeats(seatsTxt.getText());
        product.setYear(yearTxt.getText());
        product.setTransmission(transTxt.getText());
        product.setPrice(priceTxt.getText());
        product.setEngdisp(engdispTxt.getText());
        product.setSerial(serialTxt.getText());
        product.setSafety(safetyTxt.getText());
        product.setWheeltypes(wheelTxt.getText());
        product.setBrakes(brakeTxt.getText());
        product.setFilePath(filePath);
       
        JOptionPane.showMessageDialog(null,"Car details entered successfully");
        
    }//GEN-LAST:event_createButnActionPerformed

    private void safetyTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_safetyTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_safetyTxtActionPerformed

    private void uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadActionPerformed
    JFileChooser image = new JFileChooser();
    int returnVal = image.showOpenDialog(null);

    if (returnVal == JFileChooser.APPROVE_OPTION)
    {
       path.setText(image.getSelectedFile().getName());
       filePath= image.getSelectedFile().getAbsolutePath();
    }
   
    else if (returnVal == JFileChooser.CANCEL_OPTION)
    {
        JOptionPane.showMessageDialog(null,"No image Selected");
               
      
    }
       
// TODO add your handling code here:
    }//GEN-LAST:event_uploadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jlabel1;
    private javax.swing.JTextField bodyTxt;
    private javax.swing.JLabel bodytype;
    private javax.swing.JTextField brakeTxt;
    private javax.swing.JLabel brakes;
    private javax.swing.JLabel brand;
    private javax.swing.JTextField brandTxt;
    private javax.swing.JLabel color;
    private javax.swing.JTextField colorTxt;
    private javax.swing.JButton createButn;
    private javax.swing.JLabel engdisp;
    private javax.swing.JTextField engdispTxt;
    private javax.swing.JTextField fuelTxt;
    private javax.swing.JLabel fueltype;
    private javax.swing.JLabel mileage;
    private javax.swing.JTextField mileageTxt;
    private javax.swing.JLabel model;
    private javax.swing.JTextField modelTxt;
    private javax.swing.JLabel path;
    private javax.swing.JLabel price;
    private javax.swing.JTextField priceTxt;
    private javax.swing.JLabel safety;
    private javax.swing.JTextField safetyTxt;
    private javax.swing.JLabel seats;
    private javax.swing.JTextField seatsTxt;
    private javax.swing.JLabel serial;
    private javax.swing.JTextField serialTxt;
    private javax.swing.JTextField transTxt;
    private javax.swing.JLabel transmission;
    private javax.swing.JButton upload;
    private javax.swing.JTextField wheelTxt;
    private javax.swing.JLabel wheels;
    private javax.swing.JLabel year;
    private javax.swing.JTextField yearTxt;
    // End of variables declaration//GEN-END:variables
}
