/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Product;
/**
 *
 * @author saura
 */
public class MainJframe extends javax.swing.JFrame {

    /**
     * Creates new form MainJframe
     */
    private Product product;
    public MainJframe() {
        initComponents();
        product = new Product();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPanel = new javax.swing.JSplitPane();
        ControlJpanel = new javax.swing.JPanel();
        createbutn = new javax.swing.JButton();
        viewButn = new javax.swing.JButton();
        DisplayJpanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createbutn.setText("Create");
        createbutn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createbutnActionPerformed(evt);
            }
        });

        viewButn.setText("View");
        viewButn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ControlJpanelLayout = new javax.swing.GroupLayout(ControlJpanel);
        ControlJpanel.setLayout(ControlJpanelLayout);
        ControlJpanelLayout.setHorizontalGroup(
            ControlJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlJpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ControlJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createbutn)
                    .addComponent(viewButn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ControlJpanelLayout.setVerticalGroup(
            ControlJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlJpanelLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(createbutn)
                .addGap(37, 37, 37)
                .addComponent(viewButn)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        splitPanel.setLeftComponent(ControlJpanel);

        javax.swing.GroupLayout DisplayJpanelLayout = new javax.swing.GroupLayout(DisplayJpanel);
        DisplayJpanel.setLayout(DisplayJpanelLayout);
        DisplayJpanelLayout.setHorizontalGroup(
            DisplayJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );
        DisplayJpanelLayout.setVerticalGroup(
            DisplayJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );

        splitPanel.setRightComponent(DisplayJpanel);

        getContentPane().add(splitPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createbutnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createbutnActionPerformed
        CreateJpanel createPanel = new CreateJpanel(product);   
        splitPanel.setRightComponent(createPanel);
// TODO add your handling code here:
    }//GEN-LAST:event_createbutnActionPerformed

    private void viewButnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButnActionPerformed
      ViewJpanel viewPanel = new ViewJpanel(product);
      splitPanel.setRightComponent(viewPanel);
      
      // TODO add your handling code here:
    }//GEN-LAST:event_viewButnActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ControlJpanel;
    private javax.swing.JPanel DisplayJpanel;
    private javax.swing.JButton createbutn;
    private javax.swing.JSplitPane splitPanel;
    private javax.swing.JButton viewButn;
    // End of variables declaration//GEN-END:variables
}
