/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Product;
import javax.swing.ImageIcon;
/**
 *
 * @author saura
 */
public class ViewJpanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJpanel
     * @param product
     */
    public ViewJpanel(Product product) {
        initComponents();
        displayProduct(product);
        
    }
private void displayProduct(Product product)
{
    String productBrand=product.getBrand();
    brandTxt.setText(productBrand);
    
    String productModel=product.getModel();
    modelTxt.setText(productModel);
    
    String productColor=product.getColor();
    colorTxt.setText(productColor);
    
    String productFuel=product.getFueltype();
    fuelTxt.setText(productFuel);
    
    String productMileage=product.getMileage();
    mileageTxt.setText(productMileage);
    
    String productBody=product.getBodytype();
    bodyTxt.setText(productBody);
    
    String productSeats=product.getSeats();
    seatsTxt.setText(productSeats);
    
    String productYear=product.getYear();
    yearTxt.setText(productYear);
    
    String productTrans=product.getTransmission();
    transTxt.setText(productTrans);
    
    String productPrice=product.getPrice();
    priceTxt.setText(productPrice);
    
    String productEngDisp=product.getEngdisp();
    engdispTxt.setText(productEngDisp);
    
    String productSerial=product.getSerial();
    serialTxt.setText(productSerial);
    
    String productSafety=product.getSafety();
    safetyTxt.setText(productSafety);
    
    String productWheel=product.getWheeltypes();
    wheelTxt.setText(productWheel);
    
    String productBrake=product.getBrakes();
    brakeTxt.setText(productBrake);
    
    ImageIcon img = new ImageIcon(product.getFilePath());
    viewImage.setIcon(img);
    
    
   
    
    
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Jlabel1 = new javax.swing.JLabel();
        brand = new javax.swing.JLabel();
        model = new javax.swing.JLabel();
        color = new javax.swing.JLabel();
        fueltype = new javax.swing.JLabel();
        mileage = new javax.swing.JLabel();
        bodytype = new javax.swing.JLabel();
        seats = new javax.swing.JLabel();
        year = new javax.swing.JLabel();
        transmission = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        engdisp = new javax.swing.JLabel();
        mileageTxt = new javax.swing.JTextField();
        brandTxt = new javax.swing.JTextField();
        bodyTxt = new javax.swing.JTextField();
        seatsTxt = new javax.swing.JTextField();
        yearTxt = new javax.swing.JTextField();
        transTxt = new javax.swing.JTextField();
        priceTxt = new javax.swing.JTextField();
        serialTxt = new javax.swing.JTextField();
        modelTxt = new javax.swing.JTextField();
        colorTxt = new javax.swing.JTextField();
        fuelTxt = new javax.swing.JTextField();
        serial = new javax.swing.JLabel();
        engdispTxt = new javax.swing.JTextField();
        safety = new javax.swing.JLabel();
        serial2 = new javax.swing.JLabel();
        serial3 = new javax.swing.JLabel();
        wheelTxt = new javax.swing.JTextField();
        safetyTxt = new javax.swing.JTextField();
        brakeTxt = new javax.swing.JTextField();
        viewImage = new javax.swing.JLabel();

        Jlabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Jlabel1.setText("Car details");

        brand.setText("Brand");

        model.setText("Model");

        color.setText("Color");

        fueltype.setText("Fuel Type");

        mileage.setText("Mileage");

        bodytype.setText("Body Type");

        seats.setText("No. of Seats");

        year.setText("Mfg. Year");

        transmission.setText("Transmission");

        price.setText("Price");

        engdisp.setText("Engine Displacement");

        brandTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandTxtActionPerformed(evt);
            }
        });

        colorTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorTxtActionPerformed(evt);
            }
        });

        serial.setText("Serial Number");

        safety.setText("Safety Measures");

        serial2.setText("Type of Wheels");

        serial3.setText("Brake Type");

        safetyTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                safetyTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(Jlabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(transmission)
                    .addComponent(model)
                    .addComponent(brand)
                    .addComponent(color)
                    .addComponent(fueltype)
                    .addComponent(mileage)
                    .addComponent(bodytype)
                    .addComponent(seats)
                    .addComponent(year)
                    .addComponent(price)
                    .addComponent(engdisp)
                    .addComponent(serial)
                    .addComponent(safety)
                    .addComponent(serial2)
                    .addComponent(serial3))
                .addGap(105, 105, 105)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mileageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bodyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fuelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(engdispTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wheelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(safetyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brakeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(viewImage, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Jlabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brand)
                    .addComponent(brandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(model)
                            .addComponent(modelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(color)
                            .addComponent(colorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fueltype)
                            .addComponent(fuelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mileage)
                            .addComponent(mileageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bodytype)
                            .addComponent(bodyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seats)
                            .addComponent(seatsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(year)
                            .addComponent(yearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(transmission)
                            .addComponent(transTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(price)
                            .addComponent(priceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(engdisp)
                            .addComponent(engdispTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(serial)
                            .addComponent(serialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(safety)
                            .addComponent(wheelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(serial2)
                            .addComponent(safetyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(serial3)
                            .addComponent(brakeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(viewImage, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(256, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void colorTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorTxtActionPerformed

    private void brandTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandTxtActionPerformed

    private void safetyTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_safetyTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_safetyTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jlabel1;
    private javax.swing.JTextField bodyTxt;
    private javax.swing.JLabel bodytype;
    private javax.swing.JTextField brakeTxt;
    private javax.swing.JLabel brand;
    private javax.swing.JTextField brandTxt;
    private javax.swing.JLabel color;
    private javax.swing.JTextField colorTxt;
    private javax.swing.JLabel engdisp;
    private javax.swing.JTextField engdispTxt;
    private javax.swing.JTextField fuelTxt;
    private javax.swing.JLabel fueltype;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mileage;
    private javax.swing.JTextField mileageTxt;
    private javax.swing.JLabel model;
    private javax.swing.JTextField modelTxt;
    private javax.swing.JLabel price;
    private javax.swing.JTextField priceTxt;
    private javax.swing.JLabel safety;
    private javax.swing.JTextField safetyTxt;
    private javax.swing.JLabel seats;
    private javax.swing.JTextField seatsTxt;
    private javax.swing.JLabel serial;
    private javax.swing.JLabel serial2;
    private javax.swing.JLabel serial3;
    private javax.swing.JTextField serialTxt;
    private javax.swing.JTextField transTxt;
    private javax.swing.JLabel transmission;
    private javax.swing.JLabel viewImage;
    private javax.swing.JTextField wheelTxt;
    private javax.swing.JLabel year;
    private javax.swing.JTextField yearTxt;
    // End of variables declaration//GEN-END:variables
}
