/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Patient;

import Business.EcoSystem;
import Business.Enterprise.HospitalType.departmenttype;
import Business.Hospital.Doctor.Doctor;
import Business.Hospital.Lab.Lab;
import Business.Hospital.Pharmacy.Pharmacy;
import Business.Hospital.SocialEvents.SocialEvents;
import Business.Network.Network;
import Business.Role.PatientRole;
import static Business.Role.Role.RoleType.Doctor;
import Business.UserAccount.PatientAccount;
import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import userInterface.MainJFrame;

/**
 *
 * @author DAVE
 */
public class ShoppingListJpanel extends javax.swing.JPanel {

    
    private EcoSystem system;
    private JPanel container;
    private PatientAccount account;
    private Network net;
    private departmenttype dept;
    private JFrame frame;
    /**
     * Creates new form ShoppingListJpanel
     */
    public ShoppingListJpanel(EcoSystem system, Network net, JPanel container, PatientAccount account, departmenttype dept, JFrame frame) {
        initComponents();
        this.system = system;
        this.container = container;
        this.account = account;
        this.net = net;
        this.dept = dept;
        this.frame = frame;
        
        
        populateTable();
        nameLabel.setText(account.getPatient().getFirstName());
        typeLabel.setText(dept.getValue());
        areaLabel.setText(net.getId());
    }
    
    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) ShopTable.getModel();
        dtm.setRowCount(0);
        if (dept.equals(departmenttype.Pharmacy)) {
            for (Pharmacy p : net.getPharmacyList()) {
                Object row[] = new Object[2];
                row[0] = p;
                row[1] = p.getCategory();
                dtm.addRow(row);
            }
        }
        if (dept.equals(departmenttype.Lab)) {
            for (Lab Lab : net.getLabList()) {
                Object row[] = new Object[2];
                row[0] = Lab;
                row[1] = Lab.getCategory();
                dtm.addRow(row);
            }
        }
        if (dept.equals(departmenttype.Doctor)) {
            for (Doctor Doctor : net.getDoctorList()) {
                Object row[] = new Object[2];
                row[0] = Doctor;
                row[1] = Doctor.getCategory();
                dtm.addRow(row);
            }
        }
        if (dept.equals(departmenttype.Events)) {
            for (SocialEvents social : net.getEventList()) {
                Object row[] = new Object[2];
                row[0] = social;
                row[1] = social.getCategory();
                dtm.addRow(row);
            }
        }
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        detailPanel = new javax.swing.JPanel();
        areaLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ShopTable = new javax.swing.JTable();
        cartButton = new javax.swing.JButton();
        profileButton = new javax.swing.JButton();
        JPanel = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        typeLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        detailPanel2 = new javax.swing.JPanel();
        PharmacyNameLabel = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel1.setText("Welcome, ");

        detailPanel.setLayout(new java.awt.CardLayout());

        setBackground(new java.awt.Color(204, 255, 204));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        setMaximumSize(new java.awt.Dimension(1090, 650));

        areaLabel.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        areaLabel.setText("<Area>");

        jScrollPane1.setPreferredSize(new java.awt.Dimension(200, 404));

        ShopTable.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        ShopTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Category"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ShopTable.setPreferredSize(new java.awt.Dimension(200, 100));
        ShopTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShopTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ShopTable);

        cartButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        cartButton.setText("Shopping Cart");
        cartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartButtonActionPerformed(evt);
            }
        });

        profileButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        profileButton.setText("My Profile");
        profileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileButtonActionPerformed(evt);
            }
        });

        JPanel.setBackground(new java.awt.Color(153, 255, 153));
        JPanel.setPreferredSize(new java.awt.Dimension(655, 498));

        javax.swing.GroupLayout JPanelLayout = new javax.swing.GroupLayout(JPanel);
        JPanel.setLayout(JPanelLayout);
        JPanelLayout.setHorizontalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        JPanelLayout.setVerticalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        backButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        typeLabel.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        typeLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        typeLabel.setText("<Type>");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel4.setText("Hello,");

        nameLabel.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        nameLabel.setText("<Name>");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel3.setText("in ");

        detailPanel2.setLayout(new java.awt.CardLayout());

        PharmacyNameLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        PharmacyNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PharmacyNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(profileButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cartButton)))
                        .addGap(27, 27, 27)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(typeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel3)
                        .addGap(42, 42, 42)
                        .addComponent(areaLabel)
                        .addGap(106, 106, 106)
                        .addComponent(jLabel4)
                        .addGap(42, 42, 42)
                        .addComponent(nameLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(detailPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backButton)))
                .addGap(1082, 1082, 1082)
                .addComponent(JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(typeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(areaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(profileButton)
                                    .addComponent(cartButton)))
                            .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(detailPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PharmacyNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(97, 97, 97)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(119, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ShopTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShopTableMouseClicked
        int index = ShopTable.getSelectedRow();
        TableModel model = ShopTable.getModel();

        if (index >= 0) {
            if (dept.equals(departmenttype.Doctor)) {
                Doctor store = (Doctor) model.getValueAt(index, 0);
                PharmacyNameLabel.setText(store.getName());
                ShoppingDetailsJpanel panel = new ShoppingDetailsJpanel(this.system, store, this.account, net, dept);
                detailPanel2.remove(this);
                detailPanel2.add(panel);
            }
            if (dept.equals(departmenttype.Lab)) {
                Lab l = (Lab) model.getValueAt(index, 0);
                PharmacyNameLabel.setText(l.getName());
                ShoppingDetailsJpanel panel = new ShoppingDetailsJpanel(this.system, l, this.account, net, dept);
                detailPanel2.remove(this);
                detailPanel2.add(panel);
            }
            if (dept.equals(departmenttype.Pharmacy)) {
                Pharmacy l = (Pharmacy) model.getValueAt(index, 0);
                PharmacyNameLabel.setText(l.getName());
                ShoppingDetailsJpanel panel = new ShoppingDetailsJpanel(this.system, l, this.account, net, dept);
                detailPanel2.remove(this);
                detailPanel2.add(panel);
            }
            if (dept.equals(departmenttype.Events)) {
                SocialEvents l = (SocialEvents) model.getValueAt(index, 0);
                PharmacyNameLabel.setText(l.getName());
                ShoppingDetailsJpanel panel = new ShoppingDetailsJpanel(this.system, l, this.account, net, dept);
                detailPanel2.remove(this);
                detailPanel2.add(panel);
            }
            

            CardLayout layout = (CardLayout) this.detailPanel2.getLayout();
            layout.next(detailPanel2);
        }
    }//GEN-LAST:event_ShopTableMouseClicked

    private void cartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartButtonActionPerformed
        CartJFrame frame = new CartJFrame(this.system, this.account, net);
         frame.setSize(1000, 700);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }//GEN-LAST:event_cartButtonActionPerformed

    private void profileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileButtonActionPerformed
        PatientProfileJPanel panel = new PatientProfileJPanel(this.system, this.container, this.account, new PatientRole());
        this.container.add(panel);
        CardLayout layout = (CardLayout) this.container.getLayout();
        layout.next(this.container);
    }//GEN-LAST:event_profileButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        CardLayout layout = (CardLayout) this.container.getLayout();
        PatientMainJPanel cp = new PatientMainJPanel(system, container, this.account);
        this.container.add(cp);
        layout.next(this.container);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel;
    private javax.swing.JLabel PharmacyNameLabel;
    private javax.swing.JTable ShopTable;
    private javax.swing.JLabel areaLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JButton cartButton;
    private javax.swing.JPanel detailPanel;
    private javax.swing.JPanel detailPanel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton profileButton;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
