/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Pharmacy.Medicines;

import Business.DB4O.DB4O;
import Business.EcoSystem;
import Business.Enterprise.Delivery.DeliveryCompany;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalType;
import Business.Hospital.Pharmacy.Pharmacy;
import Business.Network.Network;
import Business.WorkQueue.DeliveryRequest;
import Business.WorkQueue.OrderRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author saura
 */
public class SelectDeliveryJFrame extends javax.swing.JFrame {

    private EcoSystem system;
    private JPanel panel;
    private Network net;
    private OrderRequest request;
    private HospitalType department;
    private Pharmacy pharmacy;
    private DeliveryCompany company;
    private Enterprise en;
    /**
     * Creates new form SelectDeliveryJFrame
     */
    
    public SelectDeliveryJFrame(EcoSystem system, JPanel panel, Network net, Pharmacy pharmacy,HospitalType department, OrderRequest selectedOrder, Enterprise en) {
    
        initComponents();
        this.system = system;
        this.net = net;
        this.request = selectedOrder;
        this.panel = panel;
        this.pharmacy = pharmacy;
        this.department=department;
        this.en=en;
        
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        DefaultListCellRenderer renderer = (DefaultListCellRenderer) deliveryList.getCellRenderer();
        renderer.setHorizontalAlignment(SwingConstants.CENTER);
        DefaultListModel<DeliveryCompany> model = new DefaultListModel<>();
        for(Network n : this.system.getNetworkList()){
            System.out.println(this.system.getNetworkList());
        for (DeliveryCompany del : n.getDeliveryCompanyList()) {
            System.out.println(n.getDeliveryCompanyList());
        model.addElement(del);
    }
        }
        deliveryList.setModel(model);
    }
    private void populateDeliveryCompTable(){
        
        
        for(Network n : system.getNetworkList()){
        System.out.println(n.getDeliveryCompanyList());
        for (DeliveryCompany del : n.getDeliveryCompanyList()) {
            //Object row[] = new Object[dtm.getColumnCount()];
            //row[0] = del.getID();
            //dtm.addRow(row);
        }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        selectBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        deliveryList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Select Delivery Company");

        selectBtn.setText("Select");
        selectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");

        deliveryList.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        deliveryList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                deliveryListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(deliveryList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(selectBtn)
                        .addGap(42, 42, 42)
                        .addComponent(cancelBtn)))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(54, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(204, 204, 204)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectBtn)
                    .addComponent(cancelBtn))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(64, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBtnActionPerformed
        // TODO add your handling code here:
        if (deliveryList.getSelectedValue() != null) {
            DeliveryCompany de = (DeliveryCompany) deliveryList.getSelectedValue();
            request.setCompany(de);
            request.setStatus(WorkRequest.StatusEnum.Ready);
            DeliveryRequest dr = new DeliveryRequest(department, null, request);
            dr.setStatus(WorkRequest.StatusEnum.Ready);
            de.getWorkQueue().getWorkRequestList().add(dr);
            DB4O.getInstance().storeSystem(system);
            if (panel instanceof MedicinesManagerJpanel) {
                MedicinesManagerJpanel p = (MedicinesManagerJpanel) panel;
                p.populateOrderTable();
                p.populateDetailTable(request);
            }
            
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Please select a delivery company");
        }
    }//GEN-LAST:event_selectBtnActionPerformed

    private void deliveryListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_deliveryListValueChanged

    }//GEN-LAST:event_deliveryListValueChanged

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SelectDeliveryJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SelectDeliveryJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SelectDeliveryJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SelectDeliveryJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SelectDeliveryJFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JList<DeliveryCompany> deliveryList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton selectBtn;
    // End of variables declaration//GEN-END:variables
}
