/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Car;
import Business.CarInformation;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author saura
 */
public class serialJPanel extends javax.swing.JPanel {

    /**
     * Creates new form serialJPanel
     */
    private CarInformation carInfo;
    private JPanel rightPanel;
    private int count;
    
    public serialJPanel() {
        
    }

    serialJPanel(CarInformation carInfo, JPanel rightPanel) {
        initComponents();
        this.carInfo = carInfo;
        this.rightPanel = rightPanel;
       populate(carInfo); 
    }

    public void populate(CarInformation carInfo){
        DefaultTableModel dtm = (DefaultTableModel)tblCar.getModel();
        dtm.setRowCount(0);
        
        for(Car a : carInfo.getCarDirectory()){
            Object[] row = new Object[dtm.getColumnCount()];
            row[0]=a.getBrand();
            row[1]=a.getSerial_num();
            row[2]=a.getModel_num();
            row[3]=a.getManufactured_year();
            row[4]=a.getAvailble_city();
            row[5]=a.getMin_seats();
            row[6]=a.getMax_seats();
            row[7]=a.isAvailable();
            row[8]=a.getManufacturer();
            row[9]=a.isMaintenance_certificate();
            dtm.addRow(row);
        }
        count= tblCar.getRowCount();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        serialTxt = new javax.swing.JTextField();
        serialBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCar = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setText("Enter Serial Number:");

        serialTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialTxtActionPerformed(evt);
            }
        });

        serialBtn.setText("Search");
        serialBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialBtnActionPerformed(evt);
            }
        });

        tblCar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Brand", "Serial Number", "Model Number", "Man. Year", "City", "Min Seats", "Max Seats", "Availibility", "Manufacturer", "Maintainance Certificate"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCar);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Search Based on Serial Number");

        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnBack)))
                        .addGap(0, 191, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(serialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(serialBtn)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serialBtn))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(80, 80, 80))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void serialBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serialBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm =(DefaultTableModel)tblCar.getModel();
        dtm.setRowCount(0);
        int c= 0;
        int serial= Integer.parseInt(serialTxt.getText());
        
        
        try{
            Integer.parseInt(serialTxt.getText());
        } catch(NumberFormatException e){
        JOptionPane.showMessageDialog(null,"Please enter a number for Serial Number");
        return;
        }
        for(int i=0;i<count;i++)
        {
            if(carInfo.getCarDirectory().get(i).getSerial_num()==(serial))
            {
                Car a = carInfo.addCar();
                Object[] row = new Object[dtm.getColumnCount()];
                row[0]=carInfo.getCarDirectory().get(i).getBrand();
                row[1]=carInfo.getCarDirectory().get(i).getSerial_num();
                row[2]=carInfo.getCarDirectory().get(i).getModel_num();
                row[3]=carInfo.getCarDirectory().get(i).getManufactured_year();
                row[4]=carInfo.getCarDirectory().get(i).getAvailble_city();
                row[5]=carInfo.getCarDirectory().get(i).getMin_seats();
                row[6]=carInfo.getCarDirectory().get(i).getMax_seats();
                row[7]=carInfo.getCarDirectory().get(i).isAvailable();
                row[8]=carInfo.getCarDirectory().get(i).getManufacturer();
                row[9]=carInfo.getCarDirectory().get(i).isMaintenance_certificate();
                dtm.addRow(row);
                c=c+i;
            }
        }
        if(c==0){
        JOptionPane.showMessageDialog(null, "No Car found with entered Brand");
        }
    }//GEN-LAST:event_serialBtnActionPerformed

    private void serialTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serialTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serialTxtActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        rightPanel.remove(this);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.previous(rightPanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton serialBtn;
    private javax.swing.JTextField serialTxt;
    private javax.swing.JTable tblCar;
    // End of variables declaration//GEN-END:variables
}
